### ISSUE TITLE
Provide a standard public domain license file

### ISSUE THREAD

**Issue by jfredrickson5** [GSA/GSAOpenSourcePolicy#2]
As a product owner, I want a standard public domain license file so that I can either copy it to my product's source code repository or link to it.

This would be useful for the [Code.gov "license" field](https://code.gov/#/policy-guide/docs/compliance/inventory-code), which is required to be a URL. Some projects may not have a license file accessible at a URL. By providing a standard public domain license file that applies to most projects, they can simply link to it. We would need to ensure that this file does not move (or if it moves, we provide a HTTP redirect), so that the license URLs submitted to Code.gov stay valid.

Not sure if this is the correct location for such a license file. Maybe open.gsa.gov, usa.gov, or code.gov?

**Comment by jcastle-zz** [comment]
Copied over to https://open.gsa.gov/code/ issues.  Closing because this is now a duplicate.
