### ISSUE TITLE
When sensitive content is found in commit history

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/GSAOpenSourcePolicy#4]
In the instance that passwords, api keys, or other sensitive information is committed to the code repository, what is the guidance that will we provide to teams. Is it sufficient to change the credentials and remove them from the file or is a commit history rewrite required?

**Comment by Ryandaydev** [comment]
Great addition. Here's a link I read recently on the "commit history rewrite" path.

https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by LeoCYang** [comment]
Application source code often contains a bunch of secrets such as account password, API tokens, sensitive server IPs, and private keys.   

My suggestions to manage secrets in an open source application project: 

**1. Consolidate an application’s secrets in one configuration file**
      Most of modern app project temples have a configuration file developers can utilize to store app setting and secrets.  For example, a .NET app solution has either web.config or app.config.  

**2. Exclude the configuration file from the public repo.  Erase the secrets in the repo's change history** 
      Depending on the versioning manager system your development team use, there are resources and document to guide you to exclude the file from the repository and erase the history in the code repository.  Ryan provided an good online document for GitHub in his post.  

**3. Create an example or dummy configuration file with fake data in it when you want people to know where the data coming from.**  
This will maintain your source code completeness when you release the source code to public.  For example, wp-config-sample.php is a configuration demo file in WordPress source code (https://github.com/WordPress/WordPress).

**Comment by jcastle-zz** [comment]
@afeld, can you comment here too?  I am thinking about [12Factor](https://12factor.net/), in particular principal 1 and 3 but that doesn't explain how like @LeoCYang and @rdgsa point to in previous comments.  Thinking this ties more into 18F [Before You Ship](https://before-you-ship.18f.gov/) and [Git Module for Preventing Sensitive Content](https://github.com/18F/git-seekret).

**Comment by afeld** [comment]
There are a handful related topics here:

* Cleaning a repository in order to switch it from private to public
    * https://help.github.com/articles/removing-sensitive-data-from-a-repository/
    * #5
* How to deal with sensitive information accidentally getting into a public repository
    * (very similar to above)
* How to modify the code/project to work without secrets in the codebase
    * [Twelve-Factor III: Config](https://12factor.net/config)
* How to prevent sensitive information from getting into a repository
    * https://github.com/18F/git-seekret
* How to find sensitive information in public repositories
    * https://github.com/kootenpv/gittyleaks
    * https://github.com/michenriksen/gitrob
    * (there are others)

Might help to define the scope of #5 and this issue?

**Comment by LeoCYang** [comment]
@afeld 

Thanks for sharing those links related to this topic.  

@jcastle 

This project is Open Source Policy.  Should we include best practice as well.  

I think we should organize the secrets management best practice to 

1. Greenfield project:  Many information and links can be useful to remove the secrets in the source code repo for a brand new project or a project in early stage. 

2. Brownfield project: I saw @afeld suggested in another issue -- "If the repository has any meaningful history, best practice is to copy to a new repository anyway (after removing the secrets)".  I think this is a very good recommendation for a brownfield project with significant long change history.  It would be too messy to remove the change history in a repo.

**Comment by jcastle-zz** [comment]
Moving all discussion to forked 18F repo for development of overarching GSA guidance - https://github.com/GSA/open-source-policy
