### ISSUE TITLE
Code Review Checklist - Questions to ask during code review

### ISSUE THREAD

**Issue by LeoCYang** [GSA/GSAOpenSourcePolicy#5]
Code review is one of the steps in the Open Source process.  Our team has developed a checklist for the application development project Subject-Matter Experts such as System Analysts and Programmers to review the project source code.  

1. Does the app source code contain PII or financial sensitive Information?
2. Does the app’s source code contain password? 
3. Does the app’s source code contain security management features such as security keys, encryption and decryption business logics?  

All the answers need to be ‘NO” before the project team can release the source code to public or store it in a public repo.  

I suggest that this might be code review guideline we can add to this Open Source Policy.  

Controlled Unclassified Information (CUI) is probably the updated terminology for PII or financial sensitive Information.

**Comment by Ryandaydev** [comment]
Another question to add:
Does the app source code contain 3rd party libraries that are not open source (or have a different license?)

**Comment by LeoCYang** [comment]
@rdgsa 

Good suggestion.  This should be the 4th question regarding  3rd party libraries and framework.  

4. Does the app source code contain 3rd party libraries or frameworks that are not open source (or have a different license?)

**Comment by jfredrickson5** [comment]
Possibly also ask whether the source code has ever had these PII/passwords/keys/etc in the past, because that data would still exist in the commit history.

**Comment by mogul** [comment]
> All the answers need to be ‘YES” before the project team can release the source code to public or store it in a public repo.

Surely you meant all the answers need to be NO?

**Comment by jcastle-zz** [comment]
@LeoCYang, this is a great idea, have a checklist for project teams/developers to use as they consider and release code.  Can you take the action item to build this master check sheet in markdown and place in this repo for us to link in the guidance?

**Comment by afeld** [comment]
> release the source code to public or store it in a public repo

If the repository has any meaningful history, best practice is to copy to a new repository anyway. People may have said things in issues that they assumed were only meant for a private space, for example.

---

Some useful resources:

* https://github.com/18F/seekret
* https://github.com/cfpb/open-source-checklist

**Comment by LeoCYang** [comment]
@mogul 

Thanks for pointing out the typo.  Yes, all the answers should be NO.  I fixed it. 

@jcastle 

Yes, I will created a checklist markdown page in this repo.

**Comment by jcastle-zz** [comment]
New MD file created by @LeoCYang.  Please add content there and do a pull request.
