### ISSUE TITLE
What information is considered sensitive?

### ISSUE THREAD

**Issue by Ryandaydev** [GSA/GSAOpenSourcePolicy#8]
Does source code that describes the database structure of tables at risk to an application being open sourced?

After all, someone viewing these files would learn how the underlying data is stored.

For instance:
- SQL queries for building or querying a database
- Object-Relational Mapping (ORM) configuration files

**Comment by afeld** [comment]
> someone viewing these files would learn how the underlying data is stored

And someone viewing the code would learn how the data is processed. Exposing these is kind of the point 😉 

In other words, a strong "no" from me.

**Comment by konklone** [comment]
Database schemas and knowledge of the underlying database stack is non-sensitive, and necessary to achieve the benefits of open source. 

Broadly speaking, an open source application should include everything necessary to run the application and set up your own instance. That doesn't need to include things like API keys or passwords, but does need to include database queries and schemas.

**Comment by LeoCYang** [comment]
General speaking, a database data structure shows how an app's data is stored.  SQLs describe how the app's data flow and transformation.  They should be part of open source code to benefit the public like @konklone said. 

@rdgsa , do you have a specific example of a database structure could contain secrets? Like a SQL could show business logics of encrypt/decrypt passwords, credit card numbers, or private keys?

**Comment by Ryandaydev** [comment]
@LeoCYang I think the comments above have addressed my question, thanks. I was referring to both the DDL (structure) and DML (querying) statements.

However, it does occur to me that sometimes DDL statements for table creation may include grants of rights.

Should the DDL statements be edited to remove any mentions of:
- User IDs
- Grants of rights

**Comment by afeld** [comment]
You can see 18F's list of what constitutes sensitive information [here](https://github.com/18F/open-source-policy/blob/master/practice.md#protecting-sensitive-information). User IDs and grant lists would not be considered sensitive, in my opinion, since they do not provide access to a system themselves (like a password).

**Comment by jfredrickson5** [comment]
I agree with @afeld that user IDs shouldn't be considered sensitive. However, if user IDs are hardcoded somewhere, that could indicate an architectural issue, such as needing to follow the [Config factor](https://12factor.net/config).

Database grants could be considered similar to authorization logic in the code.

**Comment by afeld** [comment]
Maybe it makes sense to rename this issue (or split out a more general one) for "what information is considered sensitive," and thus should be withheld from public repositories?

**Comment by jcastle-zz** [comment]
Moving all discussion to forked 18F repo for development of overarching GSA guidance - https://github.com/GSA/open-source-policy
