### ISSUE TITLE
VITAP

### ISSUE THREAD

**Issue by jcastle-zz** [GSA/GSAOpenSourcePolicy#9]
ICSF Open Source Software Project

**Comment by LeoCYang** [comment]
Visual Invoice and Payment (VITAP) is a project to migrate VITAP financial management system from Visual FoxPro to C#.  The project is in development phase.  The project team stores the source code in a private repo.  About 8 contributors actively adding new codes to the repo everyday.  

Here is the application's technology stack:

1. .NET Framework
2. C#
3. Entity Framework
4. LINQ
5. Kendo
6. JavaScript
7. ASP.NET Razor
8. JQuery
9. Bootstrap
10. .NET MVC
11. CSS

One of the tools in the technology stack is Kendo.  Kendo is a commercial license web UI JavaScript library.  We will need guidance on what to do with Kendo UI JavaScript when we release VITAP as an Open Source Software.

**Comment by jcastle-zz** [comment]
Moved to https://github.com/GSA/open-source-policy/issues/1
